server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
    initialization-mode: always  # Ensures initialization scripts are executed on startup
    schema: classpath:/db/schema.sql  # Path to schema SQL script
    data: classpath:/db/data.sql      # Path to data SQL script

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
